# gateway-server/docker-compose.yml
# 로컬 개발용 - 실행환경 dev
services:
  gateway-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: first-ticket-gateway
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8080
      EUREKA_SERVER_URL: eureka-server
      CONFIG_SERVER_USERNAME: ${CONFIG_SERVER_USERNAME}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://first-ticket-keycloak:8080/realms/first-ticket/protocol/openid-connect/certs
      SPRING_DATA_REDIS_HOST: first-ticket-redis
      ZIPKIN_ENDPOINT: http://first-ticket-zipkin:9411/api/v2/spans

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      start_period: 90s
      retries: 3
    restart: unless-stopped
    networks:
      - first-ticket-network

networks:
  first-ticket-network:
    external: true
    name: first-ticket-network